#!/usr/bin/env python3
"""
SharePoint CSV Uploader Script
==============================

This script uploads the four CSV files generated by daily_forecast.py to SharePoint Online
using Microsoft Graph API with App Registration (Client Credentials flow).

Files uploaded:
- actuals.csv (recent year actuals)
- predicts.csv (recent year predictions) 
- forecasts.csv (30-day forecast)
- model_metrics.csv (model performance metrics)

The script overwrites existing files daily and provides comprehensive logging.

Author: AI Assistant
Date: 2024-10-03
"""

import os
import sys
import logging
import requests
import json
from datetime import datetime
from typing import Optional, Dict, Any
from pathlib import Path
import urllib.parse

# Setup logging
def setup_logging():
    """Setup logging configuration"""
    LOG_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'logs')
    os.makedirs(LOG_DIR, exist_ok=True)
    
    log_filename = f"sharepoint_upload_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    log_path = os.path.join(LOG_DIR, log_filename)
    
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(log_path),
            logging.StreamHandler(sys.stdout)
        ]
    )
    
    logger = logging.getLogger(__name__)
    logger.info(f"SharePoint uploader logging initialized. Log file: {log_path}")
    return logger

logger = setup_logging()

class SharePointUploader:
    """
    SharePoint uploader using Microsoft Graph API with App Registration
    """
    
    def __init__(self):
        """Initialize SharePoint uploader with configuration from environment variables"""
        self.tenant_id = os.getenv('SHAREPOINT_TENANT_ID')
        self.client_id = os.getenv('SHAREPOINT_CLIENT_ID') 
        self.client_secret = os.getenv('SHAREPOINT_CLIENT_SECRET')
        
        # SharePoint site configuration
        self.site_url = os.getenv('SHAREPOINT_SITE_URL', 'https://jeanalytics.sharepoint.com/sites/LSTM')
        self.folder_path = os.getenv('SHAREPOINT_FOLDER_PATH', 'Shared Documents')
        
        # Extract site components from URL
        if 'sharepoint.com' in self.site_url:
            # Parse SharePoint URL: https://tenant.sharepoint.com/sites/sitename
            url_parts = self.site_url.replace('https://', '').split('/')
            self.hostname = url_parts[0]  # tenant.sharepoint.com
            self.site_path = '/'.join(url_parts[1:]) if len(url_parts) > 1 else ''  # sites/sitename
            self.site_name = url_parts[-1] if len(url_parts) > 2 else 'root'
        else:
            raise ValueError(f"Invalid SharePoint site URL: {self.site_url}")
        
        # Graph API endpoints
        self.graph_base_url = "https://graph.microsoft.com/v1.0"
        self.token_url = f"https://login.microsoftonline.com/{self.tenant_id}/oauth2/v2.0/token"
        
        self.access_token = None
        
        logger.info(f"SharePoint uploader initialized for site: {self.site_url}")
        logger.info(f"Target folder: {self.folder_path}")
        logger.info(f"Site hostname: {self.hostname}, site path: {self.site_path}")
        
    def validate_config(self) -> bool:
        """Validate that all required configuration is present"""
        required_vars = {
            'SHAREPOINT_TENANT_ID': self.tenant_id,
            'SHAREPOINT_CLIENT_ID': self.client_id, 
            'SHAREPOINT_CLIENT_SECRET': self.client_secret
        }
        
        missing_vars = [var for var, value in required_vars.items() if not value]
        
        if missing_vars:
            logger.error(f"Missing required environment variables: {missing_vars}")
            logger.error("Please ensure the following secrets are set in GitHub:")
            for var in missing_vars:
                logger.error(f"  - {var}")
            return False
            
        logger.info("All required configuration variables are present")
        return True
        
    def get_access_token(self) -> bool:
        """
        Get access token using client credentials flow
        """
        logger.info("Requesting access token from Microsoft Graph API")
        
        token_data = {
            'client_id': self.client_id,
            'client_secret': self.client_secret,
            'scope': 'https://graph.microsoft.com/.default',
            'grant_type': 'client_credentials'
        }
        
        try:
            response = requests.post(self.token_url, data=token_data)
            response.raise_for_status()
            
            token_response = response.json()
            self.access_token = token_response.get('access_token')
            
            if self.access_token:
                logger.info("Successfully obtained access token")
                return True
            else:
                logger.error("Access token not found in response")
                return False
                
        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to obtain access token: {e}")
            if hasattr(e, 'response') and e.response is not None:
                logger.error(f"Response content: {e.response.text}")
            return False
            
    def get_site_id_multiple_methods(self) -> Optional[str]:
        """
        Try multiple methods to get SharePoint site ID
        """
        logger.info("Trying multiple methods to get site ID")
        
        headers = {
            'Authorization': f'Bearer {self.access_token}',
            'Content-Type': 'application/json'
        }
        
        # Method 1: Direct site path approach
        try:
            logger.info("Method 1: Using direct site path")
            site_url = f"{self.graph_base_url}/sites/{self.hostname}:/{self.site_path}"
            logger.info(f"Trying URL: {site_url}")
            
            response = requests.get(site_url, headers=headers)
            if response.status_code == 200:
                site_data = response.json()
                site_id = site_data.get('id')
                if site_id:
                    logger.info(f"Method 1 successful - Site ID: {site_id}")
                    return site_id
            else:
                logger.warning(f"Method 1 failed with status {response.status_code}: {response.text}")
                
        except Exception as e:
            logger.warning(f"Method 1 failed with exception: {e}")
        
        # Method 2: Search for site by name
        try:
            logger.info("Method 2: Searching for site by name")
            search_url = f"{self.graph_base_url}/sites?search={self.site_name}"
            logger.info(f"Trying search URL: {search_url}")
            
            response = requests.get(search_url, headers=headers)
            if response.status_code == 200:
                search_data = response.json()
                sites = search_data.get('value', [])
                
                for site in sites:
                    if self.site_name.lower() in site.get('name', '').lower():
                        site_id = site.get('id')
                        if site_id:
                            logger.info(f"Method 2 successful - Found site '{site.get('name')}' with ID: {site_id}")
                            return site_id
                            
                logger.warning(f"Method 2: Site '{self.site_name}' not found in search results")
                logger.info(f"Available sites: {[site.get('name') for site in sites]}")
            else:
                logger.warning(f"Method 2 failed with status {response.status_code}: {response.text}")
                
        except Exception as e:
            logger.warning(f"Method 2 failed with exception: {e}")
        
        # Method 3: Try with URL encoding
        try:
            logger.info("Method 3: Using URL encoded path")
            encoded_path = urllib.parse.quote(f"/{self.site_path}", safe='/')
            site_url = f"{self.graph_base_url}/sites/{self.hostname}:{encoded_path}"
            logger.info(f"Trying encoded URL: {site_url}")
            
            response = requests.get(site_url, headers=headers)
            if response.status_code == 200:
                site_data = response.json()
                site_id = site_data.get('id')
                if site_id:
                    logger.info(f"Method 3 successful - Site ID: {site_id}")
                    return site_id
            else:
                logger.warning(f"Method 3 failed with status {response.status_code}: {response.text}")
                
        except Exception as e:
            logger.warning(f"Method 3 failed with exception: {e}")
        
        # Method 4: List all sites (for debugging)
        try:
            logger.info("Method 4: Listing all accessible sites for debugging")
            sites_url = f"{self.graph_base_url}/sites?$top=50"
            
            response = requests.get(sites_url, headers=headers)
            if response.status_code == 200:
                sites_data = response.json()
                sites = sites_data.get('value', [])
                
                logger.info(f"Found {len(sites)} accessible sites:")
                for i, site in enumerate(sites[:10]):  # Show first 10 sites
                    logger.info(f"  {i+1}. {site.get('name')} - {site.get('webUrl')} - ID: {site.get('id')}")
                
                # Try to find our site in the list
                for site in sites:
                    site_url_check = site.get('webUrl', '').lower()
                    if 'lstm' in site_url_check or self.site_name.lower() in site.get('name', '').lower():
                        site_id = site.get('id')
                        logger.info(f"Method 4 - Found matching site: {site.get('name')} with ID: {site_id}")
                        return site_id
                        
            else:
                logger.warning(f"Method 4 failed with status {response.status_code}: {response.text}")
                
        except Exception as e:
            logger.warning(f"Method 4 failed with exception: {e}")
        
        logger.error("All methods to get site ID failed")
        return None
            
    def get_drive_id(self, site_id: str) -> Optional[str]:
        """
        Get default drive ID for the SharePoint site
        """
        logger.info("Getting default drive ID for SharePoint site")
        
        headers = {
            'Authorization': f'Bearer {self.access_token}',
            'Content-Type': 'application/json'
        }
        
        try:
            drive_url = f"{self.graph_base_url}/sites/{site_id}/drive"
            response = requests.get(drive_url, headers=headers)
            response.raise_for_status()
            
            drive_data = response.json()
            drive_id = drive_data.get('id')
            
            if drive_id:
                logger.info(f"Successfully obtained drive ID: {drive_id}")
                return drive_id
            else:
                logger.error("Drive ID not found in response")
                return None
                
        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to get drive ID: {e}")
            if hasattr(e, 'response') and e.response is not None:
                logger.error(f"Response content: {e.response.text}")
            return None
            
    def get_folder_id(self, drive_id: str) -> Optional[str]:
        """
        Get the folder ID for the target folder, or use root if "Shared Documents"
        """
        if self.folder_path.lower() in ['shared documents', 'documents']:
            logger.info("Using root folder (Shared Documents is typically the root)")
            return None  # None means root folder
            
        logger.info(f"Getting folder ID for: {self.folder_path}")
        
        headers = {
            'Authorization': f'Bearer {self.access_token}',
            'Content-Type': 'application/json'
        }
        
        try:
            folder_path_encoded = urllib.parse.quote(self.folder_path, safe='/')
            folder_url = f"{self.graph_base_url}/drives/{drive_id}/root:/{folder_path_encoded}"
            response = requests.get(folder_url, headers=headers)
            
            if response.status_code == 200:
                folder_data = response.json()
                folder_id = folder_data.get('id')
                logger.info(f"Found folder ID: {folder_id}")
                return folder_id
            else:
                logger.warning(f"Folder not found, will use root folder. Status: {response.status_code}")
                return None
                
        except Exception as e:
            logger.warning(f"Error getting folder ID, will use root: {e}")
            return None
            
    def upload_file(self, drive_id: str, file_path: str, sharepoint_filename: str, folder_id: Optional[str] = None) -> bool:
        """
        Upload a file to SharePoint, overwriting if it exists
        """
        logger.info(f"Uploading {file_path} as {sharepoint_filename}")
        
        if not os.path.exists(file_path):
            logger.error(f"File not found: {file_path}")
            return False
            
        # Prepare headers
        headers = {
            'Authorization': f'Bearer {self.access_token}',
            'Content-Type': 'application/octet-stream'
        }
        
        try:
            # Read file content
            with open(file_path, 'rb') as file:
                file_content = file.read()
                
            # Build upload URL based on whether we have a folder ID
            if folder_id:
                upload_url = f"{self.graph_base_url}/drives/{drive_id}/items/{folder_id}:/{sharepoint_filename}:/content"
            else:
                # Upload to root
                upload_url = f"{self.graph_base_url}/drives/{drive_id}/root:/{sharepoint_filename}:/content"
            
            logger.info(f"Upload URL: {upload_url}")
            
            response = requests.put(upload_url, headers=headers, data=file_content)
            response.raise_for_status()
            
            upload_response = response.json()
            
            if upload_response.get('id'):
                file_size = len(file_content)
                web_url = upload_response.get('webUrl', 'N/A')
                logger.info(f"Successfully uploaded {sharepoint_filename} ({file_size} bytes)")
                logger.info(f"File URL: {web_url}")
                return True
            else:
                logger.error(f"Upload response missing file ID for {sharepoint_filename}")
                return False
                
        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to upload {sharepoint_filename}: {e}")
            if hasattr(e, 'response') and e.response is not None:
                logger.error(f"Response status: {e.response.status_code}")
                logger.error(f"Response content: {e.response.text}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error uploading {sharepoint_filename}: {e}")
            return False
            
    def upload_csv_files(self) -> bool:
        """
        Upload all CSV files to SharePoint
        """
        logger.info("Starting CSV files upload to SharePoint")
        
        # Define files to upload (local_filename, sharepoint_filename)
        csv_files = [
            ('actuals.csv', 'actuals.csv'),
            ('predicts.csv', 'predicts.csv'), 
            ('forecasts.csv', 'forecasts.csv'),
            ('model_metrics.csv', 'model_metrics.csv')
        ]
        
        # Get upload directory path
        project_root = os.path.dirname(os.path.dirname(__file__))
        upload_dir = os.path.join(project_root, 'data', 'upload')
        
        logger.info(f"Looking for CSV files in: {upload_dir}")
        
        # Check if upload directory exists
        if not os.path.exists(upload_dir):
            logger.error(f"Upload directory not found: {upload_dir}")
            return False
            
        # Validate configuration
        if not self.validate_config():
            return False
            
        # Get access token
        if not self.get_access_token():
            return False
            
        # Get site ID using multiple methods
        site_id = self.get_site_id_multiple_methods()
        if not site_id:
            return False
            
        # Get drive ID
        drive_id = self.get_drive_id(site_id)
        if not drive_id:
            return False
            
        # Get folder ID (optional)
        folder_id = self.get_folder_id(drive_id)
        
        # Upload each file
        upload_results = []
        
        for local_filename, sharepoint_filename in csv_files:
            local_file_path = os.path.join(upload_dir, local_filename)
            
            if not os.path.exists(local_file_path):
                logger.warning(f"File not found, skipping: {local_file_path}")
                upload_results.append(False)
                continue
                
            # Check file size
            file_size = os.path.getsize(local_file_path)
            logger.info(f"File size for {local_filename}: {file_size} bytes")
            
            if file_size == 0:
                logger.warning(f"File is empty, skipping: {local_filename}")
                upload_results.append(False)
                continue
                
            # Upload file
            success = self.upload_file(drive_id, local_file_path, sharepoint_filename, folder_id)
            upload_results.append(success)
            
        # Report results
        successful_uploads = sum(upload_results)
        total_files = len(csv_files)
        
        logger.info(f"Upload summary: {successful_uploads}/{total_files} files uploaded successfully")
        
        if successful_uploads == total_files:
            logger.info("All CSV files uploaded successfully to SharePoint")
            return True
        elif successful_uploads > 0:
            logger.warning(f"Partial success: {successful_uploads}/{total_files} files uploaded")
            return True
        else:
            logger.error("Failed to upload any files to SharePoint")
            return False


def main():
    """
    Main execution function for SharePoint upload
    """
    logger.info("=" * 60)
    logger.info("SHAREPOINT CSV UPLOAD PROCESS STARTED")
    logger.info(f"Start time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info("=" * 60)
    
    try:
        uploader = SharePointUploader()
        success = uploader.upload_csv_files()
        
        if success:
            logger.info("=" * 60)
            logger.info("SHAREPOINT CSV UPLOAD PROCESS COMPLETED SUCCESSFULLY")
            logger.info(f"End time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            logger.info("=" * 60)
        else:
            raise Exception("SharePoint upload process failed")
            
    except Exception as e:
        logger.error("=" * 60)
        logger.error("SHAREPOINT CSV UPLOAD PROCESS FAILED")
        logger.error(f"Error: {str(e)}")
        logger.error(f"End time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        logger.error("=" * 60)
        sys.exit(1)


if __name__ == "__main__":
    main()
